//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSEAktarimConsole.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TSEEntities : DbContext
    {
        public TSEEntities()
            : base("name=TSEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Sicil> Sicil { get; set; }
        public virtual DbSet<UserList> UserList { get; set; }
        public virtual DbSet<Tbl_Birimler> Tbl_Birimler { get; set; }
        public virtual DbSet<Izinler> Izinler { get; set; }
    }
}
