//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSEAktarimConsole.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserList()
        {
            this.Sicil = new HashSet<Sicil>();
        }
    
        public int ID { get; set; }
        public string UserID { get; set; }
        public int CardType { get; set; }
        public string CardID { get; set; }
        public int CardAttribute { get; set; }
        public string FacilityCode { get; set; }
        public string FingerID1 { get; set; }
        public string FingerID2 { get; set; }
        public string FPData { get; set; }
        public int UserDef { get; set; }
        public Nullable<int> Function { get; set; }
        public int Master { get; set; }
        public int BypassCard { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public string CardID26 { get; set; }
        public int IsTimezone { get; set; }
        public Nullable<bool> Deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sicil> Sicil { get; set; }
    }
}
